# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-10 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('named', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDnsRecords',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('mx_priority', models.IntegerField(blank=True, null=True)),
                ('refresh', models.IntegerField(default=300)),
                ('retry', models.IntegerField(default=3000)),
                ('expire', models.IntegerField(default=86400)),
                ('minimum', models.IntegerField(default=86400)),
                ('serial', models.BigIntegerField(default=20190710)),
                ('resp_person', models.CharField(default='admin', max_length=64)),
                ('primary_ns', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_dns_records',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TDnsXfrTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_dns_xfr_table',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='dns_record',
        ),
    ]
